spring:
  application:
    name: rule-engine-service

  datasource:
    url: jdbc:mysql://localhost:3308/rule_engine_db
    username: "eyatrooz"
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rule-engine-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

rules:
  threshold:
    amount: 1000
    name: THRESHOLD
  velocity:
    window-minutes: 10
    count: 5
    name: VELOCITY
  structuring:
    name: STRUCTURING
    window-minute: 60
    min-transactions: 3
    threshold: 1000


server:
  port: 8082

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN




