spring:
  application:
    name: case-management-service

  datasource:
    url: "jdbc:mysql://localhost:3309/case_management_db"
    username: "eyatrooz"
    password: "0000"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
