spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3307/transaction_db
    username: "eyatrooz"
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.apache.kafka.common.config.AbstractConfig: WARN